#!pip3 install fastparquet
import pandas as pd
from io import StringIO, BytesIO

# Read csv file from GCS into a variable
%gcs read --object "gs://projectcsv/compiledfulldf.csv" --variable cars

# Store in a pandas dataframe
df = pd.read_csv(BytesIO(cars),header=None,skiprows=1)

cols =[
   'Incendie_de_batiments',
 'IncendieBatiment_TrueFalse',
 'IncendieBatiment_0_1',
 'EventDate',
 'DateRange',
 'Sum_Autres_incendies',
 'Sum_Incendie_de_batiments',
 'Sum_Premier_Repondant',
 'Sum_Sans_incendie',
 'Sum_Crime',
 'Sum_Alarmes_incendies',
 'longitude',
 'latitude',
 'avg_age_population',
 'couples_no_children',
 'couples_yes_children',
 'avg_size_private_households',
 'single_detached_house',
 'apartment_building_atleast_five_storeys',
 'other_adjoining_housing',
 'twin_house',
 'twon_house',
 'apt_duplex',
 'apartment_building_less_five_storeys',
 'other_single_attached_house',
 'mobile_accomodation',
 'avg_number_rooms_dwelling',
 'before_1960',
 'f1961_1980',
 'f1981_1990',
 'f1991_2000',
 'f2001_2005',
 'f2006_2010',
 'f2011_2016',
 'regular_maintenance_minor_repairs',
 'major_repairs_needed',
 'avg_price_dwelling',
 'no_certificate_diploma_degree',
 'high_school_certificate',
 'yes_certificate_diploma_degree',
 'population_2016',
 'size_km2',
 'density',
 'total_population_age',
 'private_households_households_size',
 'f1_person',
 'f2_people',
 'f3_people',
 'f4_people',
 'f5_more_people',
 'number_people_pvate_households',
 'private_dwelling_occuped_type_dwelling',
 'private_household_tenure',
 'owner',
 'tenant',
 'occuped_private_dwelling_bedroom_qty',
 'no_bedrooms',
 'f1_bedroom',
 'f2_bedrooms',
 'f3_bedrooms',
 'f4_bedrooms',
 'occuped_private_dwelling_room_qty',
 'f1_4parts',
 'f5_pieces',
 'f6_parts',
 'f7_parts',
 'f8_parts_more',
 'occuped_private_dwelling_period_construction',
 'occuped_private_dwelling_condition_construction',
 'total_owner_households_private_ration_costincome_25p',
 'less_30p_income_housing_cost',
 'f30p_more_income_shousing_cost',
 'median_monthly_cost_owner_occupied',
 'avg_monthly_cost_owner_occupied',
 'median_value_dwellings',
 'population_private_household_immigrant_status',
 'no_immigrants',
 'immigrants',
 'no_permanent_residents',
 'immigration_population_age_immigration',
 'less_5years',
 'f5_14years',
 'f15_24years',
 'f25_44years',
 'more45years',
 'total_highest_certificate_popover15age_25p',
 'total_transporation_commute_popover15age_25p',
 'car_truck_van_driver',
 'car_truck_van_passanger',
 'public_transport',
 'walk',
 'bicycle',
 'alternate',
 'total_travel_between_work_popover15_overprivate_house_25p',
 'less_15mins',
 'f15_29mins',
 'f30_44mins',
 'f45_59mins',
 'more60mins',
 'f2015_incomestats',
 'avg_total_income2015',
 'median_total_income2015',
 'avg_aftertax_household2015',
 'median_aftertax_household2015',
 'avg_totalincome_twomorepeople_2015',
 'median_totalincome_twomorepeople_2015',
 'avg_totalincome_2015_among_beneficiaries',
 'median_totalincome_2015_among_beneficiaries',
 'avg_empoloyment_income_among_beneficiaries_2015',
 'median_empoloyment_income_among_beneficiaries_2015',
]
df.columns = cols

df.to_csv('compiledfullfixed.csv',index=False)
#df.to_parquet('compiledfullfixed.parquet.gzip', compression='gzip')

!gsutil cp compiledfullfixed.csv gs://projectcsv/compiledfullfixed.csv
